version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: npm run test:unit
      - run: npm run lint
workflows:
  test:
    jobs:
      - test
